version: "3.9"
services:
  sql-client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sql-client
    environment:
      FLINK_HOME: /opt/flink
      SQL_CLIENT_HOME: /opt/sql-client
      FLINK_JOBMANAGER_HOST: jobmanager
      ZOOKEEPER_CONNECT: zookeeper
      KAFKA_BOOTSTRAP: kafka1
      ES_HOST: es01

  jobmanager:
    image: flink:1.14.2-scala_2.11
    container_name: jobmanager
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager

  taskmanager:
    image: flink:1.14.2-scala_2.11
    container_name: taskmanager
    depends_on:
      - jobmanager
    command: taskmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 10

networks:
  elastic:
    name: elastic
    external: true
  kafka-cluster:
    name: kafka-cluster
    external: true