version: "3.9"
services:
  nuts1:
    image: &image nutsfoundation/nuts-node:latest
    container_name: nuts1
    environment:
      NUTS_CONFIGFILE: /opt/nuts/nuts.yaml
      NUTS_NETWORK_PUBLICADDR: nuts1:5555
    healthcheck:
      test: curl -f http://localhost:1323/status || exit 1
      interval: 20s
      timeout: 60s
      start_period: 15s
    ports:
      - 1323:1323
      - 5555:5555
    networks:
      - nuts-nodes
    volumes:
      - ./nuts.yaml:/opt/nuts/nuts.yaml
      - ./irma:/opt/nuts/irma:ro
      - data-node1:/opt/nuts/data

  nuts2:
    image: *image
    container_name: nuts2
    environment:
      NUTS_CONFIGFILE: /opt/nuts/nuts.yaml
    healthcheck:
      test: curl -f http://localhost:1323/status || exit 1
      interval: 20s
      timeout: 60s
      start_period: 15s
    depends_on:
      - nuts1
    ports:
      - 2323:1323
    networks:
      - nuts-nodes
    volumes:
      - ./nuts.yaml:/opt/nuts/nuts.yaml
      - ./irma:/opt/nuts/irma:ro
      - data-node2:/opt/nuts/data
  
  nuts3:
    image: *image
    container_name: nuts3
    environment:
      NUTS_CONFIGFILE: /opt/nuts/nuts.yaml
    healthcheck:
      test: curl -f http://localhost:1323/status || exit 1
      interval: 20s
      timeout: 60s
      start_period: 15s
    depends_on:
      - nuts1
    ports:
      - 3323:1323
    networks:
      - nuts-nodes
    volumes:
      - ./nuts.yaml:/opt/nuts/nuts.yaml
      - ./irma:/opt/nuts/irma:ro
      - data-node3:/opt/nuts/data

volumes:
  data-node1:
    driver: local
  data-node2:
    driver: local
  data-node3:
    driver: local

networks:
  nuts-nodes:
    name: nuts-nodes
    driver: bridge